
tabuada <- function(num, nume){
  print("Bom dia, quais números você quer ver a tabuada?")
  
  num <- readline(prompt = "Primeiro número: ")
  nume <- readline(prompt = "Segundo número: ")
  
  num <- as.integer(num)
  
  res0 <- paste("Tabuado do", num, "===")
  res1 <- paste(num, "x 1 =", num*1)
  res2 <- paste(num, "x 2 =", num*2)
  res3 <- paste(num, "x 3 =", num*3)
  res4 <- paste(num, "x 4 =", num*4)
  res5 <- paste(num, "x 5 =", num*5)
  res6 <- paste(num, "x 6 =", num*6)
  res7 <- paste(num, "x 7 =", num*7)
  res8 <- paste(num, "x 8 =", num*8)
  res9 <- paste(num, "x 9 =", num*9)
  res10 <- paste(num, "x 10 =", num*10)
  
  print(res0)
  print(res1)
  print(res2)
  print(res3)
  print(res4)
  print(res5)
  print(res6)
  print(res7)
  print(res8)
  print(res9)
  print(res10)
  
  nume <- as.integer(nume)
  
  resp0 <- paste("Tabuado do", nume, "===")
  resp1 <- paste(nume, "x 1 =", nume*1)
  resp2 <- paste(nume, "x 2 =", nume*2)
  resp3 <- paste(nume, "x 3 =", nume*3)
  resp4 <- paste(nume, "x 4 =", nume*4)
  resp5 <- paste(nume, "x 5 =", nume*5)
  resp6 <- paste(nume, "x 6 =", nume*6)
  resp7 <- paste(nume, "x 7 =", nume*7)
  resp8 <- paste(nume, "x 8 =", nume*8)
  resp9 <- paste(nume, "x 9 =", nume*9)
  resp10 <- paste(nume, "x 10 =", nume*10)
  
  print(resp0)
  print(resp1)
  print(resp2)
  print(resp3)
  print(resp4)
  print(resp5)
  print(resp6)
  print(resp7)
  print(resp8)
  print(resp9)
  print(resp10)
}
tabuada()
